sudo: required

git:
  depth: 3

services:
  - docker

install:
  - docker build --tag bernard-uguen/reversy:latest .

script:
  - docker run --name reversy bernard-uguen/reversy:latest /bin/bash -c "cd /opt/reversy;pytest tests/"

after_script:
  - docker images